src/objects/Affiliation__c.object
<CustomObject>
    <description>Connection between a Contact and an Account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The organization this person is affiliated with.</description>
        <inlineHelpText>The organization this person is affiliated with.</inlineHelpText>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliated Contacts</relationshipLabel>
        <relationshipName>Affl_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Course_Enrollment__c.object
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Academic Program that the student or faculty member is associated with.</description>
        <inlineHelpText>The Academic Program that the student or faculty member is associated with.</inlineHelpText>
        <label>Contact&apos;s Academic Program</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course Connections</relationshipLabel>
        <relationshipName>Course_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Affiliation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this Contact is affiliated with an Academic Program through an existing Program Enrollment record, and that Program Enrollment is related to this Course Connection, this Affiliation field is auto-populated with the Program Enrollment's Affiliation. If both conditions aren&apos;t true, then this Affiliation field is left blank.</description>
        <inlineHelpText>The Academic Program associated with this Course Connection. Represents a Contact-Account Affiliation.</inlineHelpText>
        <label>Affiliation</label>
        <referenceTo>Affiliation__c</referenceTo>
        <relationshipLabel>Course Connection</relationshipLabel>
        <relationshipName>Course_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For students, their primary Program Enrollment. In Higher Ed, this typically represents a student's academic major.</description>
        <inlineHelpText>For students, their primary Program Enrollment. In Higher Ed, this typically represents a student&apos;s academic major.</inlineHelpText>
        <label>Program Enrollment ID</label>
        <referenceTo>Program_Enrollment__c</referenceTo>
        <relationshipLabel>Course Connections</relationshipLabel>
        <relationshipName>Course_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

unpackaged/pre/course_connection_record_types/objects/Course_Enrollment__c.object
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>A Student Course Connection</description>
        <label>Student</label>
    </recordTypes>

src/objects/Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact's enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program the student is enrolled in.</description>
        <inlineHelpText>The Program the student is enrolled in.</inlineHelpText>
        <label>Program</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Enrollments</relationshipLabel>
        <relationshipName>Program_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Affiliation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is auto-populated with the Affiliation record that represents the student's enrollment in this Program. </description>
        <inlineHelpText>This field is auto-populated with the Affiliation record that represents the student's enrollment in this Program. </inlineHelpText>
        <label>Affiliation</label>
        <referenceTo>Affiliation__c</referenceTo>
        <relationshipLabel>Program Enrollments</relationshipLabel>
        <relationshipName>Program_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CCON_AffiliationBackfill_BATCH.cls
public class CCON_AffiliationBackfill_BATCH implements Database.Batchable<SObject>{
	
    public Database.Querylocator start(Database.BatchableContext bc) {
        Id studentCCRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        System.debug('CCON_BATCH METHOD-->'); 
        String query = 'SELECT Id, Program_Enrollment__c ' + 
                        'FROM Course_Enrollment__c ' + 
            			'WHERE Affiliation__c = NULL AND Program_Enrollment__c != NULL AND RecordTypeId = :studentCCRecordTypeId'; 
        System.debug('CCON_BATCH -->' + query); 
        return Database.getQueryLocator(query);  
    }
    
    public void execute(Database.BatchableContext bc, List<Course_Enrollment__c> returnCourseEnrollments){
        List<Id> pEnrollmentID = new List<Id>(); 
        List<Course_Enrollment__c> courseEnrollmentsToUpdate = new List<Course_Enrollment__c>(); 
        
        if (returnCourseEnrollments.size () > 0) {
            
            for (Integer i = 0; i < returnCourseEnrollments.size(); i++) {
                Course_Enrollment__c enroll = returnCourseEnrollments[i];
                if (enroll.Program_Enrollment__c != NULL) {
                    pEnrollmentID.add(enroll.Program_Enrollment__c); 
                }
            }
            
            if (pEnrollmentID.size () > 0) {
                List<Program_Enrollment__c> queryPE = [SELECT Id, Affiliation__c, Account__c
                                                  FROM Program_Enrollment__c 
                                                  WHERE Id = :pEnrollmentID]; 
                Map<Id, Program_Enrollment__c> pEnrollmentsMap = new Map<Id, Program_Enrollment__c>(queryPE); 
                
                for (Course_Enrollment__c courseEnroll : returnCourseEnrollments) {
                    courseEnroll.Affiliation__c = pEnrollmentsMap.get(courseEnroll.Program_Enrollment__c).Affiliation__c;
                    courseEnroll.Affiliation__c = pEnrollmentsMap.get(courseEnroll.Program_Enrollment__c).Account__c;
                    courseEnrollmentsToUpdate.add(courseEnroll); 
                }
                
            }
        }
        
        if (courseEnrollmentsToUpdate.size() > 0) {
            System.debug('CCON_BATCH B4Update ->' + courseEnrollmentsToUpdate); 
            update courseEnrollmentsToUpdate;
        }
    }
    
    public void finish(Database.BatchableContext bc) {}
}