src/objects/Course_Offering__c.object
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <fields>
        <fullName>Time_Block__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Time Block record that represents the start and end times for this Course Offering.</description>
        <label>Time Block</label>
        <referenceTo>Time_Block__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Time_Blocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course_Offering_Schedule__c.object
<CustomObject>
    <description>Joins Course Offering to Time Block and provides a way to specify the days and location for a Course.</description>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course Offering this schedule is for.</description>
        <inlineHelpText>The Course Offering this schedule is for.</inlineHelpText>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>Course Offering Schedules</relationshipLabel>
        <relationshipName>Course_Offering_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>The time of day the Course Offering ends. If you&apos;ve entered a Time Block for this Course Offering, you can leave this field blank.</description>
        <inlineHelpText>The time of day the Course Offering ends. If you&apos;ve entered a Time Block for this Course Offering, you can leave this field blank.</inlineHelpText>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>The time of day the Course Offering starts. If you&apos;ve entered a Time Block for this Course Offering, you can leave this field blank.</description>
        <inlineHelpText>The time of day the Course Offering starts. If you&apos;ve entered a Time Block for this Course Offering, you can leave this field blank.</inlineHelpText>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Time_Block__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Time Block in which this Course Offering is being held.</description>
        <inlineHelpText>The Time Block in which this Course Offering is being held.</inlineHelpText>
        <label>Time Block</label>
        <referenceTo>Time_Block__c</referenceTo>
        <relationshipLabel>Course Offering Schedules</relationshipLabel>
        <relationshipName>Course_Offering_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Offering Schedule</label>
    <nameField>
        <displayFormat>CSH-{000000}</displayFormat>
        <label>Course Offering Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offering Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Block__c.object
<CustomObject>
    <description>Represents a block of time in which classes are held.</description>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>The time of day the Time Block ends.</description>
        <inlineHelpText>The time of day the Time Block ends.</inlineHelpText>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>The time of day the Time Block starts.</description>
        <inlineHelpText>The time of day the Time Block starts.</inlineHelpText>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <label>Time Block</label>
    <nameField>
        <label>Time Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asynchronous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this module should be run asynchronously in this transaction</description>
        <inlineHelpText>Indicates that this module should be run asynchronously in this transaction</inlineHelpText>
        <label>Asynchronous</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owned_by_Namespace__c</fullName>
        <description>Enter the namespace of the package or Org that will control this Trigger handler.</description>
        <label>Owned by Namespace</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/TB_StartEndTime_TEST.cls
/*
    Copyright (c) 2019, Salesforce.org
    All rights reserved.
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2019
* @group Course Offering
* @group-content ../../ApexDocContent/CourseOfferings.htm
* @description Tests specific to testing the TB_StartEndTime_TDTM logic around updating the Start Time 
* and End Time on associated Course Offering Schedule records when the Time Block Start Time and/or
* End Time is updated.
*/
@isTest
private class TB_StartEndTime_TEST {
    
    private static Course_Offering__c courseOffering;
    private static Course_Offering_Schedule__c courseOfferingSchedule;
    private static Time_Block__c timeBlock;

    private static Time startTime = Time.newInstance(8, 0, 0, 0);
    private static Time endTime = Time.newInstance(10, 0, 0, 0);

    /*******************************************************************************************************
    * @description Inserts a Course Offering and Time Block record for testing. Instantiates a new
    * Course Offering Schedule record but does not insert it.
    * @param sTime The Start Time for the Time Block.
    * @param eTime The End Time for the Time Block.
    ********************************************************************************************************/
    private static void setup(Time sTime, Time eTime) {
        courseOffering = UTIL_UnitTestData_TEST.createCourseOffering(null, null);
        timeBlock = UTIL_UnitTestData_TEST.createTimeBlock(sTime, eTime);

        courseOfferingSchedule = new Course_Offering_Schedule__c(Course_Offering__c = courseOffering.Id, Time_Block__c = timeBlock.Id);
        insert courseOfferingSchedule;
    }

    /*******************************************************************************************************
    * @description Asserts that the given Start Time and End Time match the Start Time and End Time on the
    * Course Offering Schedule test record.
    * @param expectedStartTime The expected Start Time.
    * @param expectedEndTime The expected End Time.
    ********************************************************************************************************/
    private static void assertTimes(Time expectedStartTime, Time expectedEndTime) {
        Course_Offering_Schedule__c queriedCourseOfferingSchedule = [SELECT Start_Time__c, End_Time__c FROM Course_Offering_Schedule__c WHERE Id = :courseOfferingSchedule.Id];
        System.assertEquals(expectedStartTime, queriedCourseOfferingSchedule.Start_Time__c, 'The Course Offering Schedule Start Time was not set as expected.');
        System.assertEquals(expectedEndTime, queriedCourseOfferingSchedule.End_Time__c, 'The Course Offering Schedule End Time was not set as expected.');
    }

    /*******************************************************************************************************
    * @description Tests that when the Time Block's Start Time is changed, any Course Offering Schedule tied
    * to that Time Block record is also updated with the new Start Time.
    ********************************************************************************************************/
    @isTest
    private static void updateTimeBlockStartTimeUpdatesCourseOfferingSchedules() {
        setup(null, null);

        assertTimes(null, null);

        Test.startTest();
        timeBlock.Start_Time__c = Time.newInstance(3, 0, 0, 0);
        update timeBlock;
        Test.stopTest();

        assertTimes(Time.newInstance(3, 0, 0, 0), null);
    }

    /*******************************************************************************************************
    * @description Tests that when the Time Block's End Time is changed, any Course Offering Schedule tied
    * to that Time Block record is also updated with the new End Time.
    ********************************************************************************************************/
    @isTest
    private static void updateTimeBlockEndTimeUpdatesCourseOfferingSchedules() {
        setup(null, null);

        assertTimes(null, null);

        Test.startTest();
        timeBlock.End_Time__c = Time.newInstance(3, 0, 0, 0);
        update timeBlock;
        Test.stopTest();

        assertTimes(null, Time.newInstance(3, 0, 0, 0));
    }

    /*******************************************************************************************************
    * @description Tests that when the Time Block's Start Time and End Time is changed, any Course Offering 
    * Schedule tied to that Time Block record is also updated with the new Start Time and End Time.
    ********************************************************************************************************/
    @isTest
    private static void updateTimeBlockTimesUpdatesCourseOfferingSchedules() {
        setup(startTime, endTime);

        assertTimes(startTime, endTime);

        Test.startTest();
        timeBlock.Start_Time__c = Time.newInstance(1, 0, 0, 0);
        timeBlock.End_Time__c = Time.newInstance(3, 0, 0, 0);
        update timeBlock;
        Test.stopTest();

        assertTimes(Time.newInstance(1, 0, 0, 0), Time.newInstance(3, 0, 0, 0));

        System.assert(TB_StartEndTime_TDTM.reentrancyPrevented != true, 
            'Did not expect the reentrancy check to have prevented the TB_StartEndTime_TDTM trigger from processing again.');
    }

    /*******************************************************************************************************
    * @description Tests that when the Time Block update causes Course Offering Schedules to update, any 
    * custom logic that might recursively update Time Block records does not run the Time Block TDTM logic
    * again. Reentrancy into the TB_StartEndTime_TDTM class is prevented.
    ********************************************************************************************************/
    @isTest
    private static void updateTimeBlockTimesUpdatesCourseOfferingSchedulesReentrancyCheck() {
        // Install Default EDA TDTM Configuration
        List<TDTM_Global_API.TdtmToken> defaultTokens = TDTM_Global_API.getDefaultTdtmConfig();
        TDTM_Global_API.setTdtmConfig(defaultTokens, 'hed');

        // Add the Test TDTM for the Course Offering Schedule object. This Test TDTM will simply 
        // update the Time Block that caused the Course Offering Schedule to be updated.
        // So the flow would be: Time Block updated -> Course Offering Schedule updated -> Time Block updated again
        Trigger_Handler__c newTDTM = new Trigger_Handler__c(Active__c = true, Asynchronous__c = false,
            Class__c = 'UTIL_UnitTestData_TEST.Test_TDTM', Load_Order__c = 1, Object__c = 'Course_Offering_Schedule__c',
            Owned_by_Namespace__c = 'hed', Trigger_Action__c = 'AfterUpdate');
        insert newTDTM;
        
        setup(startTime, endTime);
        assertTimes(startTime, endTime);

        Test.startTest();
        timeBlock.Start_Time__c = Time.newInstance(1, 0, 0, 0);
        timeBlock.End_Time__c = Time.newInstance(3, 0, 0, 0);

        // Ensure that the Time Block gets updated recursively
        UTIL_UnitTestData_TEST.sObjectsToUpdate = new List<SObject>{ timeBlock };

        update timeBlock;
        Test.stopTest();

        assertTimes(Time.newInstance(1, 0, 0, 0), Time.newInstance(3, 0, 0, 0));

        System.assert(TB_StartEndTime_TDTM.reentrancyPrevented == true, 
            'Expected the reentrancy check to have prevented the TB_StartEndTime_TDTM trigger from processing again.');
    }
}