src/objects/Course__c.object
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course_Offering__c.object
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <fields>
        <fullName>Course__c</fullName>
        <description>Lookup to the Course record that this Course Offering is associated with.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Requirement__c.object
<CustomObject>
    <description>This object will be the various course requirements that would need to be met to achieve the particular Program Plan</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course associated with this Plan Requirement. Leave blank for a parent Plan Requirement with nested Plan Requirements.</description>
        <inlineHelpText>The Course associated with this Plan Requirement. Leave blank for a parent Plan Requirement with nested Plan Requirements.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Plan Requirements</relationshipLabel>
        <relationshipName>Plan_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the Plan Requirement is one of multiple requirements or multiple levels of requirements, specifies the parent Plan Requirement. Use this field to group a list of optional Courses that satisfy a generic requirement.</description>
        <inlineHelpText>If the Plan Requirement is one of multiple requirements or multiple levels of requirements, specifies the parent Plan Requirement. Use this field to group a list of optional Courses that satisfy a generic requirement.</inlineHelpText>
        <label>Parent Plan Requirement</label>
        <referenceTo>Plan_Requirement__c</referenceTo>
        <relationshipLabel>Plan Requirements</relationshipLabel>
        <relationshipName>Plan_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan Requirement</label>
    <nameField>
        <label>Plan Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/COUR_CannotDelete_TDTM.cls
/*
    Copyright (c) 2020, Salesforce.org
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2020
* @group Course
* @group-content ../../ApexDocContent/Course.htm
* @description Stops a Course from being deleted if it has any Course Offering or Plan Requirement child records.
*/
public with sharing class COUR_CannotDelete_TDTM extends TDTM_Runnable {
    /*******************************************************************************************************
    * @description Get the setting of preventing Course deletion
    */
    private static Boolean enabledPreventCourseDeletion = UTIL_CustomSettingsFacade.getSettings().Prevent_Course_Deletion__c;
    
    /*******************************************************************************************************
    * @description Stops a Course from being deleted if it has any Course Offering 
    * or Plan Requirement child records.
    * @param listNew the list of Courses from trigger new.
    * @param listOld the list of Courses from trigger old.
    * @param triggerAction which trigger event (BeforeInsert, AfterInsert, etc.).
    * @param objResult the describe for Courses
    * @return dmlWrapper.
    ********************************************************************************************************/
    public override DmlWrapper run(List<SObject> newlist, List<SObject> oldlist,
    TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {

        if (!COUR_CannotDelete_TDTM.enabledPreventCourseDeletion) {
            return new DmlWrapper(); 
        }

        Map<Id, Course__c> oldMap = new Map<Id, Course__c>((List<Course__c>)oldList);

        if (triggerAction == TDTM_Runnable.Action.BeforeDelete) {
            for (Course__c course : [SELECT ID,
                        (SELECT ID FROM Course__c.Course_Offerings__r LIMIT 1),
                        (SELECT ID FROM Course__c.Plan_Requirements__r LIMIT 1)
                        FROM Course__c
                        WHERE ID IN :oldlist])
            {
                if (this.hasChildRecords(course)) {
                    Course__c courseInContext = oldmap.get(course.ID);
                    courseInContext.addError(Label.CannotDelete);
                }
            }
        }

    return new DmlWrapper();
    }

    /*******************************************************************************************************
    * @description Evaluates whether the Course has any child related records.
    * @param course is the current Course record.
    * @return Boolean.
    ********************************************************************************************************/
    @testVisible
    private Boolean hasChildRecords(Course__c course) {
        return (!course.Course_Offerings__r.isEmpty() || !course.Plan_Requirements__r.isEmpty());
    }
}