src/objects/Course_Enrollment__c.object
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course Offering the student or faculty member is involved with.</description>
        <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
        <label>Course Offering ID</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>Course Connection</relationshipLabel>
        <relationshipName>Course_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Course_Offering__c.object
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Facility associated with the Course Offering.</description>
        <inlineHelpText>The Facility where this Course Offering will take place.</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course_Offering_Schedule__c.object
<CustomObject>
    <description>Joins Course Offering to Time Block and provides a way to specify the days and location for a Course.</description>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course Offering this schedule is for.</description>
        <inlineHelpText>The Course Offering this schedule is for.</inlineHelpText>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>Course Offering Schedules</relationshipLabel>
        <relationshipName>Course_Offering_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The location of the scheduled Course Offering.</description>
        <inlineHelpText>The location of the scheduled Course Offering.</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Course Offering Schedules</relationshipLabel>
        <relationshipName>Course_Offering_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to indicate this Course Offering is on Mondays. You can select multiple days.</description>
        <inlineHelpText>Select to indicate this Course Offering is on Mondays. You can select multiple days.</inlineHelpText>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to indicate this Course Offering is on Thursdays. You can select multiple days.</description>
        <inlineHelpText>Select to indicate this Course Offering is on Thursdays. You can select multiple days.</inlineHelpText>
        <label>Thursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to indicate this Course Offering is on Tuesdays. You can select multiple days.</description>
        <inlineHelpText>Select to indicate this Course Offering is on Tuesdays. You can select multiple days.</inlineHelpText>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to indicate this Course Offering is on Wednesdays. You can select multiple days.</description>
        <inlineHelpText>Select to indicate this Course Offering is on Wednesdays. You can select multiple days.</inlineHelpText>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>Course Offering Schedule</label>
    <nameField>
        <displayFormat>CSH-{000000}</displayFormat>
        <label>Course Offering Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offering Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hierarchy_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All hierarchy settings.</description>
    <fields>
        <fullName>Account_Processor__c</fullName>
        <description>ID of the default record type for Account. For example, if specifying Administrative (the recommended Account model), enter the ID of the Administrative record type for the Account object.</description>
        <inlineHelpText>ID of the default record type for Account. For example, if specifying Administrative (the recommended Account model), enter the ID of the Administrative record type for the Account object.</inlineHelpText>
        <label>Account Processor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Admin_Account_Naming_Format__c</fullName>
        <inlineHelpText>This is the setting for admin account naming format</inlineHelpText>
        <label>Admin Account Naming Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Automatic_Household_Naming__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the system will provide automatic naming for Household Names, Informal and Formal Greetings.</description>
        <inlineHelpText>If checked, the system will provide automatic naming for Household Names, Informal and Formal Greetings.</inlineHelpText>
        <label>Automatic Household Naming</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Error_Handling__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, EDA&apos;s error handling framework is disabled.</description>
        <inlineHelpText>If checked, EDA&apos;s error handling framework is disabled.</inlineHelpText>
        <label>Disable Error Handling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Household_Account_Naming_Format__c</fullName>
        <inlineHelpText>This is the setting for household account naming format</inlineHelpText>
        <label>Household Account Naming Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reciprocal_Method__c</fullName>
        <description>Determines method used to generate the reciprocal relationship.  Either List Setting which uses custom settings by gender, or Value Inversion, which inverts the type if appropriate (&quot;Parent-Child&quot; to &quot;Child-Parent&quot;)</description>
        <inlineHelpText>Determines method used to generate the reciprocal relationship.  Either List Setting which uses custom settings by gender, or Value Inversion, which inverts the type if appropriate (&quot;Parent-Child&quot; to &quot;Child-Parent&quot;)</inlineHelpText>
        <label>Reciprocal Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Errors_On__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag that indicates whether errors are going to be stored in the database.</description>
        <inlineHelpText>Check this if you&apos;d like errors to be stored in the database.</inlineHelpText>
        <label>Store Errors</label>
        <type>Checkbox</type>
    </fields>
    <label>Hierarchy Settings</label>
</CustomObject>

src/objects/Plan_Requirement__c.object
<CustomObject>
    <description>This object will be the various course requirements that would need to be met to achieve the particular Program Plan</description>
    <fields>
        <fullName>Plan_Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the Plan Requirement is one of multiple requirements or multiple levels of requirements, specifies the parent Plan Requirement. Use this field to group a list of optional Courses that satisfy a generic requirement.</description>
        <inlineHelpText>If the Plan Requirement is one of multiple requirements or multiple levels of requirements, specifies the parent Plan Requirement. Use this field to group a list of optional Courses that satisfy a generic requirement.</inlineHelpText>
        <label>Parent Plan Requirement</label>
        <referenceTo>Plan_Requirement__c</referenceTo>
        <relationshipLabel>Plan Requirements</relationshipLabel>
        <relationshipName>Plan_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan Requirement</label>
    <nameField>
        <label>Plan Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asynchronous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this module should be run asynchronously in this transaction</description>
        <inlineHelpText>Indicates that this module should be run asynchronously in this transaction</inlineHelpText>
        <label>Asynchronous</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Managed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The record is managed by the user and updates won&apos;t be pushed to it.</description>
        <inlineHelpText>Check it if you intent to manage the record yourself. Be aware that updates to the package won&apos;t update the record.</inlineHelpText>
        <label>User Managed</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/UTIL_OrgTelemetry_TEST.cls
/*
    Copyright (c) 2019, Salesforce.org
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2019
* @group Utilities
* @group-content ../../ApexDocContent/Utilities.htm
* @description Contains unit tests for testing the UTIL_OrgTelemetry and UTIL_OrgTelemetry_BATCH functionality.
*/
@isTest
private class UTIL_OrgTelemetry_TEST {

    private static UTIL_FeatureManagement_TEST.Mock featureManagementMock = new UTIL_FeatureManagement_TEST.Mock();

    /*******************************************************************************************************
    * @description Executes the EDA Telemetry batch job and asserts that it runs properly.
    ********************************************************************************************************/
    @isTest
    private static void validateTelemetryBatchJob() {
        Test.startTest();
        UTIL_OrgTelemetry.dispatchTelemetryBatchJob();
        Test.stopTest();

        System.assertEquals(true, UTIL_OrgTelemetry_BATCH.jobProcessed, 'Expected the EDA Telemetry batch job to process.');
    }

    /*******************************************************************************************************
    * @description Calls the processTelemetryType() method of the UTIL_OrgTelemetry class outside of the
    * context of the batch job to synchronously process the EDA_Settings batch category. Asserts that the
    * system sends the telemetry data to the UTIL_FeatureManagement wrapper class.
    ********************************************************************************************************/
    @IsTest
    private static void validateEDASettingsTelemetry() {
        Hierarchy_Settings__c edaSettings = UTIL_CustomSettingsFacade.getSettings();
        
        UTIL_FeatureManagement_TEST.Mock featureManagerMock = new UTIL_FeatureManagement_TEST.Mock();
        UTIL_OrgTelemetry orgTelemetry = new UTIL_OrgTelemetry();
        orgTelemetry.featureManager = (UTIL_FeatureManagement)Test.createStub(UTIL_FeatureManagement.class, featureManagerMock);

        Test.startTest();
        orgTelemetry.processTelemetryType(UTIL_OrgTelemetry.TelemetryBatchCategory.EDA_Settings);
        Test.stopTest();

        System.assertEquals(
            0,
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountCampaignMemberRelationshipRules.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountCampaignMemberRelationshipRules'
        );

        System.assertEquals(
            0,
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountContactRelationshipRules.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountContactRelationshipRules'
        );

        System.assertEquals(
            edaSettings.Automatic_Household_Naming__c,
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.IsEnabled_AutomaticHouseholdNaming.name()
            ),
            'setPackageBooleanValue should have been called with the feature IsEnabled_AutomaticHouseholdNaming'
        );

        System.assertEquals(
            UTIL_CustomSettingsFacade.courseConnectionsEnabled(),
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.IsEnabled_CourseConnections.name()
            ),
            'setPackageBooleanValue should have been called with the feature IsEnabled_CourseConnections'
        );

        System.assertEquals(
            edaSettings.Account_Processor__c == UTIL_Describe.getAdminAccRecTypeID(),
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.HasDefaultAdministrativeAccountModel.name()
            ),
            'setPackageBooleanValue should have been called with the feature HasDefaultAdministrativeAccountModel'
        );

        System.assertEquals(
            edaSettings.Account_Processor__c == UTIL_Describe.getHhAccRecTypeID(),
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.HasDefaultHouseholdAccountModel.name()
            ),
            'setPackageBooleanValue should have been called with the feature HasDefaultHouseholdAccountModel'
        );

        System.assertEquals(
            edaSettings.Disable_Error_Handling__c == false,
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.IsEnabled_ErrorHandling.name()
            ),
            'setPackageBooleanValue should have been called with the feature IsEnabled_ErrorHandling'
        );

        System.assertEquals(
            edaSettings.Admin_Account_Naming_Format__c == Label.acctNamingOther,
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.HasCustomAdministrativeAccountNaming.name()
            ),
            'setPackageBooleanValue should have been called with the feature HasCustomAdministrativeAccountNaming'
        );

        System.assertEquals(
            edaSettings.Household_Account_Naming_Format__c == Label.acctNamingOther,
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.HasCustomHouseholdAccountNaming.name()
            ),
            'setPackageBooleanValue should have been called with the feature HasCustomHouseholdAccountNaming'
        );

        System.assertEquals(
            edaSettings.Reciprocal_Method__c == 'Value Inversion',
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.HasValueInversionReciprocalMethod.name()
            ),
            'setPackageBooleanValue should have been called with the feature HasValueInversionReciprocalMethod'
        );

        System.assertEquals(
            edaSettings.Store_Errors_On__c,
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.IsEnabled_StoreErrors.name()
            ),
            'setPackageBooleanValue should have been called with the feature IsEnabled_StoreErrors'
        );
    }

    /*******************************************************************************************************
    * @description Calls the processTelemetryType() method of the UTIL_OrgTelemetry class outside of the
    * context of the batch job to synchronously process the Org_Environment batch category. Asserts that the
    * system sends the telemetry data to the UTIL_FeatureManagement wrapper class.
    ********************************************************************************************************/
    @IsTest
    private static void validateOrgEnvironmentTelemetry() {
        // Set one of the EDA TDTM classes to inactive.
        List<Trigger_Handler__c> defaultTDTM = TDTM_DefaultConfig.getDefaultRecords();
        defaultTDTM[0].Active__c = false;
        insert defaultTDTM;

        // Create a new user-managed TDTM class.
        Trigger_Handler__c userManagedHandler = new Trigger_Handler__c(
            Active__c = true,
            Asynchronous__c = false,
            Class__c = 'Test TDTM',
            Load_Order__c = 1,
            Object__c = 'Contact',
            Trigger_Action__c = 'BeforeInsert;BeforeUpdate',
            User_Managed__c = true
        );
        insert userManagedHandler;

        UTIL_FeatureManagement_TEST.Mock featureManagerMock = new UTIL_FeatureManagement_TEST.Mock();
        UTIL_OrgTelemetry orgTelemetry = new UTIL_OrgTelemetry();
        orgTelemetry.featureManager = (UTIL_FeatureManagement)Test.createStub(UTIL_FeatureManagement.class, featureManagerMock);

        Test.startTest();
        orgTelemetry.processTelemetryType(UTIL_OrgTelemetry.TelemetryBatchCategory.Org_Environment);
        Test.stopTest();

        System.assertEquals(
            3,
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Org_CountActiveCourseConnectionRecordTypes.name()
            ),
            'setPackageIntegerValue should have been called with the feature Org_CountActiveCourseConnectionRecordTypes'
        );

        System.assertEquals(
            true,
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.HasEDAInactiveTDTM.name()
            ),
            'setPackageBooleanValue should have been called with the feature HasEDAInactiveTDTM'
        );

        System.assertEquals(
            true,
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.HasUserManagedTDTM.name()
            ),
            'setPackageBooleanValue should have been called with the feature HasUserManagedTDTM'
        );

        System.assertEquals(
            false,
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.UsingOldContactEthnicity.name()
            ),
            'setPackageBooleanValue should have been called with the feature UsingOldContactEthnicity'
        );

        // TODO:
        /*System.assertNotEquals(
            null,
            featureManagerMock.packageBooleanValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.UsingOldCourseDescription.name()
            ),
            'setPackageBooleanValue should have been called with the feature UsingOldCourseDescription'
        );*/
    }

    /*******************************************************************************************************
    * @description Calls the processTelemetryType() method of the UTIL_OrgTelemetry class outside of the
    * context of the batch job to synchronously process the Object_Usage batch category. Asserts that the
    * system sends the telemetry data to the UTIL_FeatureManagement wrapper class.
    ********************************************************************************************************/
    @IsTest
    private static void validateObjectUsageTelemetry() {
        Integer expectedAdministrativeAccounts = 5;
        Integer expectedHouseholdAccounts = 3;

        List<Contact> contacts = UTIL_UnitTestData_TEST.getMultipleTestContacts(expectedAdministrativeAccounts);
        insert contacts;

        // Insert a few household accounts.
        List<Account> householdAccounts = UTIL_UnitTestData_TEST.getMultipleTestAccounts(expectedHouseholdAccounts, UTIL_Describe.getHhAccRecTypeID());
        insert householdAccounts;

        // Insert a few more random accounts.
        List<Account> businessAccounts = UTIL_UnitTestData_TEST.getMultipleTestAccounts(10, UTIL_Describe.getBizAccRecTypeID());
        insert businessAccounts;

        // Insert other random test records to test the object usage telemetry - course offerings, course connections, etc.
        Course_Offering__c courseOffering = UTIL_UnitTestData_TEST.createCourseOffering(null, null);

        List<Course_Enrollment__c> courseConnections = new List<Course_Enrollment__c>();
        for (Contact contact : contacts) {
            courseConnections.add(UTIL_UnitTestData_TEST.getCourseConnection(contact.Id, courseOffering.Id));
        }
        insert courseConnections;

        List<Course_Offering_Schedule__c> courseOfferingSchedules = new List<Course_Offering_Schedule__c>();
        courseOfferingSchedules.add(new Course_Offering_Schedule__c(Course_Offering__c = courseOffering.Id, Monday__c = true));
        courseOfferingSchedules.add(new Course_Offering_Schedule__c(Course_Offering__c = courseOffering.Id, Tuesday__c = true));
        courseOfferingSchedules.add(new Course_Offering_Schedule__c(Course_Offering__c = courseOffering.Id, Wednesday__c = true));
        courseOfferingSchedules.add(new Course_Offering_Schedule__c(Course_Offering__c = courseOffering.Id, Thursday__c = true));
        insert courseOfferingSchedules;

        List<Error__c> errors = UTIL_UnitTestData_TEST.getListOfErrors(25);
        insert errors;

        List<Facility__c> facilities = new List<Facility__c>{ UTIL_UnitTestData_TEST.getFacility() };
        insert facilities;

        List<Plan_Requirement__c> planRequirements = UTIL_UnitTestData_TEST.getMultipleTestPlanRequirements(30);
        insert planRequirements;

        List<Program_Plan__c> programPlans = UTIL_UnitTestData_TEST.getMultipleTestProgramPlans(12);
        insert programPlans;
        
        UTIL_FeatureManagement_TEST.Mock featureManagerMock = new UTIL_FeatureManagement_TEST.Mock();
        UTIL_OrgTelemetry orgTelemetry = new UTIL_OrgTelemetry();
        orgTelemetry.featureManager = (UTIL_FeatureManagement)Test.createStub(UTIL_FeatureManagement.class, featureManagerMock);

        Test.startTest();
        orgTelemetry.processTelemetryType(UTIL_OrgTelemetry.TelemetryBatchCategory.Object_Usage);
        Test.stopTest();

        System.assertEquals(
            expectedAdministrativeAccounts,
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountAdministrativeAccounts.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountAdministrativeAccounts'
        );

        System.assertEquals(
            expectedHouseholdAccounts,
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountHouseholdAccounts.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountHouseholdAccounts'
        );

        System.assertEquals(
            courseConnections.size(),
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountCourseConnections.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountCourseConnections'
        );

        System.assertEquals(
            courseOfferingSchedules.size(),
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountCourseOfferingSchedules.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountCourseOfferingSchedules'
        );

        System.assertEquals(
            errors.size(),
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountErrorLog.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountErrorLog'
        );

        System.assertEquals(
            facilities.size(),
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountFacilities.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountFacilities'
        );

        System.assertEquals(
            planRequirements.size(),
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountPlanRequirements.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountPlanRequirements'
        );

        System.assertEquals(
            programPlans.size(),
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountProgramPlans.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountProgramPlans'
        );

        System.assertEquals(
            0,
            featureManagerMock.packageIntegerValuesByName.get(
                UTIL_OrgTelemetry.TelemetryParameterName.Data_CountTermGrades.name()
            ),
            'setPackageIntegerValue should have been called with the feature Data_CountTermGrades'
        );
    }
}