src/objects/Relationship_Lookup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Provides table of gendered and gender-neutral reciprocal relationships for various relationship types (ie. Father-Son, Father-Daughter, Father-Child)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this reciprocal lookup is active.</description>
        <inlineHelpText>Indicates if this reciprocal lookup is active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Female__c</fullName>
        <description>The value used for the Reciprocal Setting if the Contact's Gender or Salutation field indicates Female gender.</description>
        <inlineHelpText>The value used for the Reciprocal Setting if the Contact's Gender or Salutation field indicates Female gender.</inlineHelpText>
        <label>Female</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Male__c</fullName>
        <description>The value used for the Reciprocal Setting if the Contact's Gender or Salutation field indicates Male gender.</description>
        <inlineHelpText>The value used for the Reciprocal Setting if the Contact's Gender or Salutation field indicates Male gender.</inlineHelpText>
        <label>Male</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Neutral__c</fullName>
        <description>The value used if the Contact&apos;s Gender and Saluation fields don't indicate gender.</description>
        <inlineHelpText>The value used if the Contact&apos;s Gender and Saluation fields don't indicate gender.</inlineHelpText>
        <label>Neutral</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Relationship Lookup</label>
</CustomObject>

src/classes/MODL_ReciprocalRelationshipMapping.cls
/*
    Copyright (c) 2020, Salesforce.org
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2020
* @group Relationships
* @group-content ../../ApexDocContent/Relationships.htm
* @description Model for Reciprocal Relationship Mappings.
*/
public with sharing class MODL_ReciprocalRelationshipMapping {
    private String relationshipName; 
    private Boolean isActive; 
    private String femaleRelationshipType; 
    private String maleRelationshipType; 
    private String neutralRelationshipType; 

    public MODL_ReciprocalRelationshipMapping(Relationship_Lookup__c relationshipLookup) {
        this.relationshipName = relationshipLookup.Name;
        this.isActive = relationshipLookup.Active__c;
        this.femaleRelationshipType = relationshipLookup.Female__c;
        this.maleRelationshipType = relationshipLookup.Male__c;
        this.neutralRelationshipType = relationshipLookup.Neutral__c;         
    }

    public String getRelationshipName() {
        return this.relationshipName;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public String getFemaleRelationshipType() {
        return this.femaleRelationshipType;
    }

    public String getMaleRelationshipType() {
        return this.maleRelationshipType;
    }

    public String getNeutralRelationshipType() {
        return this.neutralRelationshipType;
    }

    public Boolean hasFemaleValue() {
        return this.femaleRelationshipType != null;
    }

    public Boolean hasMaleValue() {
        return this.maleRelationshipType != null;
    }
}