unpackaged/test_packaged/relationship_autocreate/objects/Contact.object
<CustomObject>  
</CustomObject>

unpackaged/pre/contact_record_types/objects/Contact.object
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>Business contact.</description>
        <label>Business Contact</label>
    </recordTypes>

src/objects/Hierarchy_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>All hierarchy settings.</description>
    <fields>
        <fullName>Reciprocal_Method__c</fullName>
        <description>Determines method used to generate the reciprocal relationship.  Either List Setting which uses custom settings by gender, or Value Inversion, which inverts the type if appropriate (&quot;Parent-Child&quot; to &quot;Child-Parent&quot;)</description>
        <inlineHelpText>Determines method used to generate the reciprocal relationship.  Either List Setting which uses custom settings by gender, or Value Inversion, which inverts the type if appropriate (&quot;Parent-Child&quot; to &quot;Child-Parent&quot;)</inlineHelpText>
        <label>Reciprocal Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Hierarchy Settings</label>
</CustomObject>

unpackaged/config/trial/objects/Relationship__c.object
<CustomObject>
    <description>Connection between two Contacts.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Select the person you want to create the Relationship record for.</description>
        <inlineHelpText>Select the person you want to create the Relationship record for.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReciprocalRelationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Reciprocal Relationship record. This field is automatically populated. Manually updating this field could result in errors.</description>
        <inlineHelpText>Lookup to the related Reciprocal Relationship record. This field is automatically populated. Manually updating this field could result in errors.</inlineHelpText>
        <label>Reciprocal Relationship</label>
        <referenceTo>Relationship__c</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the person related to the Contact.</description>
        <inlineHelpText>Select the person related to the Contact.</inlineHelpText>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hidden Relationships List</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Describes how the Related Contact is connected to the Contact, for example, friend, coworker, aunt, etc.</description>
        <inlineHelpText>Describes how the Related Contact is connected to the Contact, for example, friend, coworker, aunt, etc.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Stepfather</fullName>
                </value>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Stepmother</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Stepparent</fullName>
                </value>
                <value>
                    <fullName>Foster Parent</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Stepdaughter</fullName>
                </value>
                <value>
                    <fullName>Foster Daughter</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Stepson</fullName>
                </value>
                <value>
                    <fullName>Foster Son</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Stepchild</fullName>
                </value>
                <value>
                    <fullName>Foster Child</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Grandson</fullName>
                </value>
                <value>
                    <fullName>Granddaughter</fullName>
                </value>
                <value>
                    <fullName>Grandchild</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/config/trial/objects/Relationship_Auto_Create__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Automatically generates a Relationship between a Contact and another Contact or a Contact and a Contact/Campaign Member based on a custom lookup field.</description>
    <fields>
        <fullName>Campaign_Types__c</fullName>
        <description>List of eligible Campaign types for this Campaign Member auto-create. (Will be blank for Contact auto-create)</description>
        <inlineHelpText>Eligible Campaign types for this Campaign Member auto-create. (Will be blank for Contact auto-create)</inlineHelpText>
        <label>Campaign Types</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <description>The field insert or update that triggers the creation of this Relationship</description>
        <inlineHelpText>The field insert or update that triggers the creation of this Relationship</inlineHelpText>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>The object this Auto-Relationship is associated with</description>
        <inlineHelpText>The object this Auto-Relationship is associated with</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <description>The Relationship type to be created between the base object and the lookup object.  The lookup object will receive the reciprocal Relationship, if one is available.</description>
        <inlineHelpText>The Relationship type to be created between the base object and the lookup object.  The lookup object will receive the reciprocal Relationship, if one is available.</inlineHelpText>
        <label>Relationship Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Relationship Auto-Create</label>
</CustomObject>

force-app/main/default/classes/REL_Relationships_Con_TEST.cls
/*
    Copyright (c) 2020 Salesforce.org
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2020
* @group Contact Relationships
* @group-content ../../ApexDocContent/Relationships.htm
* @description Testing for the Contact Relationship trigger functionality.
*/
@isTest
public with sharing class REL_Relationships_Con_TEST {

    /*********************************************************************************************************
    ********************************** AFTER INSERT - FUNCTIONAL TESTS ***************************************
    *********************************************************************************************************/

    // /*********************************************************************************************************
    // * @description Test method for campaign member auto create relationships
    // */
    // @isTest
    // public static void testAutoCreateCampaignMemberInsert() {
    //     setupRelationshipTestData(null);

    //     //Insert a campaign
    //     Campaign campaign = new Campaign(Name = 'TestCampaign', IsActive = true, Type = 'Other');
    //     insert campaign;

    //     //Insert a campaign member
    //     CampaignMember cm = new CampaignMember(ContactId = c2.Id, CampaignId = campaign.Id);
    //     Test.startTest();
    //     insert cm;
    //     Test.stopTest();

    //     //Verify a relationship was automatically created when the campaign member was created
    //     List<Relationship__c> relationships = [SELECT Id, Type__c FROM Relationship__c
    //                                     WHERE Contact__c = :c2.Id];
    //     UTIL_Debug.debug('****Number of relationships after creating campaign member: ' + relationships.size());
    //     system.assertEquals(2, relationships.size());
    //     system.assertEquals('TestType', relationships[0].Type__c);

    //     //Verify a reciprocal relationship was also automatically created when the campaign member was created
    //     List<Relationship__c> reciprocalRelationships = [SELECT Id, Type__c FROM Relationship__c
    //                                     WHERE ReciprocalRelationship__c = :relationships[0].Id];
    //     UTIL_Debug.debug('****Number of reciprocal relationships: ' + reciprocalRelationships);
    //     system.assertEquals(1, reciprocalRelationships.size());
    //     system.assertEquals('TestType', reciprocalRelationships[0].Type__c);
    // }

    // /*********************************************************************************************************
    // * @description Test method for campaign member auto create relationships - synchronous
    // */
    // @isTest
    // public static void testAutoCreateCampaignMemberInsertSynch() {
    //     setupRelationshipTestData(new Hierarchy_Settings__c(Reciprocal_Method__c = 'List Setting'));

    //     //insert a campaignmember
    //     Campaign c = new Campaign(Name = 'TestCampaign', IsActive = true, Type = 'Other');
    //     insert c;
    //     CampaignMember cm = new CampaignMember(ContactId = c2.Id, CampaignId = c.Id);

    //     Test.startTest();
    //     insert cm;
    //     Test.stopTest();

    //     Relationship__c rel = [SELECT Id, Type__c FROM Relationship__c WHERE Contact__c = :c2.Id LIMIT 1];
    //     system.assertEquals('TestType', rel.Type__c);
    //     Relationship__c recRel = [SELECT Id, Type__c FROM Relationship__c WHERE ReciprocalRelationship__c = :rel.Id];
    //     system.assertEquals('TestType', recRel.Type__c);
    // }

    // /*********************************************************************************************************
    // * @description Test method for verifying automatic relationship creation won't create a duplicate.
    // */
    // @isTest
    // public static void testAutoCreateDupePrevention() {
    //     setupRelationshipTestData(null);

    //     List<Relationship__c> crel = new List<Relationship__c>{
    //         new Relationship__c(Contact__c = c1.Id, RelatedContact__c = c2.Id, Type__c = 'TestType')
    //     };
    //     crel.add(new Relationship__c(Contact__c = c1.Id, RelatedContact__c = c2.Id, Type__c = 'TestType2'));
    //     insert crel;

    //     //update the ReportsToId to trigger autocreation
    //     c1.ReportsToId = c2.Id;

    //     Test.startTest();
    //     update c1;
    //     Test.stopTest();

    //     //assert we only have one relationship since we've deduped the auto-created one
    //     List<Relationship__c> rel = [SELECT Id, Type__c, RelatedContact__c FROM Relationship__c WHERE Contact__c = :c1.Id AND Type__c = 'TestType'];
    //     system.assertEquals('TestType', rel[0].Type__c);
    //     system.assertEquals(rel.size(), 1);
    // }

    // /*********************************************************************************************************
    // * @description Test method for REL_Utils class when auto create settings exist
    // */
    // @isTest
    // public static void testRelationshipUTILSAutoCreate() {
    //     System.runAs(new User(Id = UserInfo.getUserId())) {
    //         insert new Relationship_Auto_Create__c(Name = 'contacttest'+ system.now(),
    //                                                 Object__c = 'Contact', Field__c = 'coworker__c',
    //                                                 Relationship_Type__c = 'coworker',
    //                                                 Campaign_Types__c = 'fun event');
    //         insert new Relationship_Auto_Create__c(Name = 'membertest'+ system.now(),
    //                                                 Object__c = 'CampaignMember', Field__c = 'member__c',
    //                                                 Relationship_Type__c = 'member',
    //                                                 Campaign_Types__c = 'fun event');

    //         Boolean cAuto = REL_Utils.hasContactAutoCreate;
    //         Boolean cmAuto = REL_Utils.hasCMAutoCreate;
    //         System.assertEquals(true, cAuto);
    //         System.assertEquals(true, cmAuto);
    //     }
    // }
}