force-app/main/default/objects/Product_Registry__mdt/Product_Registry__mdt.object-meta.xml
<CustomObject>
    <description>Defines a product tile or a tool in the EDA Cloud Settings page</description>
    <label>Product Registry</label>
    <pluralLabel>Product Registries</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Registry__mdt/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Defines the specific Action or Category this registry refers to.</description>
    <label>Action</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Registry__mdt/fields/Api_Version__c.field-meta.xml
<CustomField>
    <fullName>Api_Version__c</fullName>
    <description>The API version to use while calling the product method</description>
    <label>Api Version</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Registry__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>The class name to call for this specific product</description>
    <label>Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Registry__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <description>Defines the product namespace for this registry. For example: hed,sfal,etc.</description>
    <label>Namespace</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/interoperability/classes/ProductRegistryMapper_TEST.cls
@isTest
private class ProductRegistryMapper_TEST {
    @isTest
    private static void testGetProductRegistrySettingsProductInformation() {
        String action = 'testAction';
        String namespace = 'testNamespace';
        String classname = 'testClassname';
        Decimal apiVersion = 50.0;

        ProductRegistryMapper.instance = new ProductRegistryMapperStub();
        List<ProductRegistryModel> prodRegistryModelList;

        Test.startTest();
        prodRegistryModelList = ProductRegistryMapper.getInstance().getProductRegistrySettingsProductInformation();
        Test.stopTest();

        System.assert(prodRegistryModelList != null, 'prodRegistryModelList should not be null');
        System.assert(!prodRegistryModelList.isEmpty(), 'prodRegistryModelList should not be empty');
        System.assertEquals(1, prodRegistryModelList.size(), 'prodRegistryModelList should have 1 element');

        ProductRegistryModel model = prodRegistryModelList.get(0);

        System.assertEquals(action, model.action, 'action should be set with the value: ' + action);
        System.assertEquals(namespace, model.namespace, 'namespace should be set with the value: ' + namespace);
        System.assertEquals(classname, model.classname, 'classname should be set with the value: ' + classname);
        System.assertEquals(apiVersion, model.apiVersion, 'apiVersion should be set with the value: ' + apiVersion);
    }

    @isTest
    private static void testJustForCoverage() {
        List<ProductRegistryModel> prodRegistryModelList;
        Test.startTest();
        prodRegistryModelList = ProductRegistryMapper.getInstance().getProductRegistrySettingsProductInformation();
        Test.stopTest();
    }

    private class ProductRegistryMapperStub extends ProductRegistryMapper {
        public override List<Product_Registry__mdt> getProductRegistriesByAction(String action) {
            Product_Registry__mdt prodRegistryCMT = new Product_Registry__mdt();
            prodRegistryCMT.Action__c = 'testAction';
            prodRegistryCMT.Namespace__c = 'testNamespace';
            prodRegistryCMT.Class_Name__c = 'testClassname';
            prodRegistryCMT.API_Version__c = 50.0;
            return new List<Product_Registry__mdt>{ prodRegistryCMT };
        }
    }
}